### ISSUE TITLE
Create issue with features/enhancement

### ISSUE THREAD

**Issue by mrbatista** [duffn/loopback-connector-arango#5]
It would be appropriate to know which features the connector supports, those of which it is lacking and what is the roadmap for the new features.
I'd like to contribute with PRs.

**Comment by nvdnkpr** [comment]
Hello Nick, hello Matteo,
as the original author I am very happy that there are more ArangoDB and Loopback enthusiasts out there. I built the first version of the connector as a Proof Of Concept for a small project, but didn't found the time to go deeper. Also I thought I would be the only user.
I am thrilled that my connector found the way into a Strongloop blog post.

ArangoDB changed a few nice API Features for [v2.4](https://docs.arangodb.com/NewFeatures/NewFeatures24.html) and [v2.5](https://docs.arangodb.com/NewFeatures/NewFeatures25.html) , especially when using AQL and they also published an Query Builder for AQL. 
The major API changes that was baked into the new controller is the possibility to return the affected documents when using modifying AQL queries (CREATE, UPDATE, REMOVE), so that is now possible to return the created, update, removed doc ID. 

This change and the release of the AQB, the [AQL Query Builder](https://github.com/arangodb/aqbjs), lead me to build the it a new version, which you can find [here](https://github.com/nvdnkpr/loopback-connector-arango/tree/NewVersion). 

So to make it short: 
There is a dedicated [query](https://github.com/nvdnkpr/loopback-connector-arango/blob/NewVersion/src/arango.coffee#L250) method for querying via AQL and a dedicated [transaction](https://github.com/nvdnkpr/loopback-connector-arango/blob/NewVersion/src/arango.coffee#L231) method to execute a query as a transaction. All other CRUD methods build either one query (only exception is the UPSERT like behaviour of the updateOrCreate/save methods, which need two AQL queries and are executed as a transaction).

TODOs (for a roadmap of issues)
- Tests (I ported the tests from e.g. mongo connector, but I am open to write them from scratch if necessary) 
- Loopback currently executes a second query when using inclusion of related models. With the power of AQL this could also be modeled with one single query, which can nests the other including model in a a subquery
- In the upcoming there will be a new UPSERT command which then makes it possible to model the createOrUpdate query with just one AQL query. 

@mrbatista @duffn:
Take a look and leave me comment, perhaps we could sit down and talk something like a roadmap.

**Comment by duffn** [comment]
@nvdnkpr 
Hello, 

First, thank you for the great ArangoDB connector. I forked it as the NPM registry and Github were out of sync and NPM had the most recent version, but it would be great to get your repo updated and use that one. I'll happily contribute to your repo but I don't believe I'm going to have the time to maintain this one - and you clearly know more than I when it comes to Arango!

I'll be happy to update the blog post as well to your repo when that time comes.

**Comment by nvdnkpr** [comment]
@duffn @mrbatista 
It's always good to know that there more people sharing the same passion for something. I'll rearrange my repository and move issues and things over.

@mrbatista 
Love to hear some more input and as you said contributions then.

**Comment by duffn** [comment]
@nvdnkpr 
Great! Let me know if there's anything I can do to help you switch over to your repo.

**Comment by mrbatista** [comment]
@nvdnkpr I had a look to your new branch (at the moment you removed all code of your repo).
I answer to your TODOs list:
1. MongoDB test connector is a good start; then it will be necessary to write custom tests to cover all the new features.
2. This is an improvement for me. It would be suitable to create a benchmark for testing performance and making the appropriate changes.
3. I would wait version 2.6 to remove your workaround.

These are my comments on the functionality that the driver must have:
1. Support to arangojs driver >3.0.0 (ok in your new version)
2. Support for transactions (at the moment loopback supports transactions for RDBMS databases only) verify the feasibility for NoSQL databases.
3. Support for CRUD operations for edge.
4. Support for custom queries.
4. Support for graph queries.
5. Support to clustering (Any project with intensive data requests necessitates a clustering structure).
4. Support to native driver like [this](https://github.com/strongloop/loopback-connector-mysql/blob/master/lib/mysql.js#L21).

Given the impossibility of @duffn to support the development of the project, we have two options:
1. becoming maintainers of the repo
2. switch the development of the driver to your original repo
this is only a brainstorming, it would be appropriate to deepen the various open points and then to split the tasks between us.
I would be happy to support the development of this connector.

**Comment by nvdnkpr** [comment]
@mrbatista 
I wanted a clean fresh start, and with a semver compatible 0.1.0 version so I removed the repo and created a new one which currently contains the initial commit from github with an License and a README file, [Link](https://github.com/nvdnkpr/loopback-connector-arangodb).

I initiated it from scratch with the gitflow model (tagged releases on "master", development in "feature-XXX" branches, releases in "release-XXX" branches and so on).

I will commit later the new version later on develop as version number 0.1.0.

**Comment by mrbatista** [comment]
:+1:

**Comment by nvdnkpr** [comment]
@mrbatista @duffn 
I created an issue for our initial version. Also added you both as collaborators to the repo. 

@mrbatista 
Since you created the issues here, could you move your created issues to the other repo ? Just C&P, perhaps with some additional info. Extend it with the list that you wrote in the previous comment.
I think I already have some of your features (custom queries, transactions) in there. If so just refer to my ticket. I will make an feature branch for that ticket and publish it now, so you can see what will go into v0.1.0.

**Comment by duffn** [comment]
All issues moved to https://github.com/nvdnkpr/loopback-connector-arangodb.
